import {sha256} from 'js-sha256';
export const fields=['features','bug_fixes','changed_behaviour','qa_summary','known_limitations','migration_notes','affected_groups'] as const;
export const labels:Record<Field,string>={features:'Features',bug_fixes:'Bug fixes',changed_behaviour:'Changed behaviour',qa_summary:'QA summary',known_limitations:'Known limitations',migration_notes:'Migration notes',affected_groups:'Affected groups'};
export type Field=typeof fields[number]; export type Item={id:string;field:Field;text:string;hash:string}; export type Package=Record<Field,string[]>; export const prefix:Record<Field,string>={features:'F',bug_fixes:'B',changed_behaviour:'C',qa_summary:'QA',known_limitations:'L',migration_notes:'M',affected_groups:'G'};
export const hash=(s:string)=>sha256(s.trim()).slice(0,16);
export function normalize(p:Partial<Package>):Package {const out={} as Package; for(const f of fields){const xs=Array.isArray(p[f])?p[f]!:[]; out[f]=xs.map(x=>String(x).trim()).filter(Boolean).flatMap(x=>/^(none|n\/a)$/i.test(x)?[]:[x]);} return out;}
export function makeItems(pkg:Package,old:Item[]=[]):Item[]{const out:Item[]=[]; for(const f of fields){const previous=old.filter(i=>i.field===f), unused=new Set(previous.map(i=>i.id)), exact=new Map<string,Item[]>(); for(const i of previous){const a=exact.get(i.text)||[]; a.push(i);exact.set(i.text,a);} const pending:string[]=[]; for(const text of pkg[f]){const match=exact.get(text)?.find(i=>unused.has(i.id)); if(match){unused.delete(match.id);out.push({id:match.id,field:f,text,hash:hash(text)});}else pending.push(text);} const pool=previous.filter(i=>unused.has(i.id)); let max=previous.reduce((m,i)=>Math.max(m,Number(i.id.slice(prefix[f].length))||0),0); for(let n=0;n<pending.length;n++){const id=pool[n]?.id||`${prefix[f]}${++max}`; out.push({id,field:f,text:pending[n],hash:hash(pending[n])});}}return out;}
const stop=new Set('with from that this have will your into about after before when then than were been being does what them they their there which while tested tests test user users using used able only also more less'.split(' '));
const words=(s:string)=>new Set((s.toLowerCase().match(/[a-z]{4,}/g)||[]).filter(w=>!stop.has(w)));
export type Check={severity:'error'|'warning';code:string;message:string;items:string[]};
export function checks(pkg:Package,items:Item[]):Check[]{const out:Check[]=[];for(const f of fields)if(!pkg[f].length)out.push({severity:'error',code:'missing_section',message:`Add items to ${labels[f]} or write "None".`,items:[]}); const qa=items.filter(i=>i.field==='qa_summary'); for(const i of items.filter(i=>['features','bug_fixes','changed_behaviour'].includes(i.field))){const w=words(i.text);if(!qa.some(q=>[...words(q.text)].some(x=>w.has(x))))out.push({severity:'warning',code:'no_qa_evidence',message:`${i.id} has no meaningful keyword in common with QA evidence.`,items:[i.id,...qa.map(q=>q.id)]});}if(pkg.changed_behaviour.length&&!pkg.migration_notes.length)out.push({severity:'warning',code:'behaviour_without_migration',message:'Changed behaviour is listed but migration notes are empty.',items:items.filter(i=>i.field==='changed_behaviour').map(i=>i.id)});for(const q of qa)if(/\b(fail(?:ed|ing)?|skipped|not tested|untested|flaky)\b/i.test(q.text))out.push({severity:'warning',code:'qa_reports_gap',message:`QA reports a gap: ${q.text}`,items:[q.id]});return out;}
export function diff(a:Item[],b:Item[]){const A=new Map(a.map(i=>[i.id,i])),B=new Map(b.map(i=>[i.id,i]));return {added:b.filter(i=>!A.has(i.id)),removed:a.filter(i=>!B.has(i.id)),changed:b.filter(i=>A.has(i.id)&&A.get(i.id)!.text!==i.text).map(i=>({id:i.id,before:A.get(i.id)!.text,after:i.text}))};}
export function isStale(s:{kind:string;cites:string[];cite_hashes:Record<string,string>;scope_hash?:string},latest:Item[],latestPkg:Package):string[]{const map=new Map(latest.map(i=>[i.id,i.hash])); const stale=s.cites.filter(id=>map.get(id)!==s.cite_hashes[id]);const scope=s.kind==='unsupported_claim'?hash(JSON.stringify(latest.filter(i=>i.field==='qa_summary').map(i=>[i.id,i.hash]))):s.kind==='missing_info'?hash(JSON.stringify(latest.map(i=>[i.id,i.hash]))):'';if(scope&&scope!==s.scope_hash)stale.push('package scope');return stale;}
