import express from 'express';import cors from 'cors';import {db} from './db.js';import {checks,diff,fields,Item,makeItems,normalize,Package,isStale,hash} from './core.js';import {generate,AIError,scopeHash} from './ai.js';import {z} from 'zod';import {join} from 'node:path';
const app=express();app.use(cors());app.use(express.json({limit:'4mb'}));app.use(express.static(join(process.cwd(),'dist/public')));
const error=(res:any,status:number,message:string)=>res.status(status).json({error:message});const pkgOf=(v:any)=>JSON.parse(v.package) as Package;const itemsOf=(v:any)=>JSON.parse(v.items) as Item[];const latest=(rid:number)=>db.prepare('SELECT * FROM versions WHERE release_id=? ORDER BY version_no DESC LIMIT 1').get(rid) as any;
function statementRows(vid:number){return db.prepare('SELECT * FROM statements WHERE version_id=? ORDER BY id').all(vid).map((s:any)=>{const v=db.prepare('SELECT release_id FROM versions WHERE id=?').get(vid) as any;const l=latest(v.release_id),stale_cites=l?isStale({kind:s.kind,cites:JSON.parse(s.cites),cite_hashes:JSON.parse(s.cite_hashes),scope_hash:s.scope_hash||undefined},itemsOf(l),pkgOf(l)):[];return {...s,text:s.edited_text??s.text,cites:JSON.parse(s.cites),stale:stale_cites.length>0,stale_cites};});}
app.post('/api/releases',(req,res)=>{const p=z.object({name:z.string().trim().min(1).max(150)}).safeParse(req.body);if(!p.success)return error(res,422,'Enter a release name.');const info=db.prepare('INSERT INTO releases(name) VALUES(?)').run(p.data.name);console.log(JSON.stringify({event:'release_created',release_id:info.lastInsertRowid}));res.status(201).json({id:info.lastInsertRowid,name:p.data.name});});app.get('/api/releases',(_req,res)=>res.json(db.prepare('SELECT * FROM releases ORDER BY id DESC').all()));
app.post('/api/releases/:rid/versions',(req,res)=>{const r=db.prepare('SELECT * FROM releases WHERE id=?').get(req.params.rid);if(!r)return error(res,404,'Release not found.');const raw=req.body?.package;if(!raw||typeof raw!=='object')return error(res,422,'Provide a release package.');for(const f of fields){if(!Array.isArray(raw[f]))return error(res,422,`Each ${f} value must be a list.`);if(raw[f].length>200||raw[f].some((x:any)=>typeof x!=='string'||x.length>2000))return error(res,422,'Each section supports up to 200 items of 2,000 characters each.');}const pkg=normalize(raw),prior=latest(Number(req.params.rid)),items=makeItems(pkg,prior?itemsOf(prior):[]),version_no=(db.prepare('SELECT COALESCE(MAX(version_no),0)+1 n FROM versions WHERE release_id=?').get(req.params.rid) as any).n;const info=db.prepare('INSERT INTO versions(release_id,version_no,package,items) VALUES(?,?,?,?)').run(req.params.rid,version_no,JSON.stringify(pkg),JSON.stringify(items));console.log(JSON.stringify({event:'version_saved',version_id:info.lastInsertRowid,release_id:req.params.rid,version_no}));res.status(201).json({id:info.lastInsertRowid,version_no,package:pkg,items,checks:checks(pkg,items)});});
app.get('/api/releases/:rid/versions',(req,res)=>res.json(db.prepare('SELECT id,release_id,version_no,created_at,reviewed_by FROM versions WHERE release_id=? ORDER BY version_no DESC').all(req.params.rid)));
app.get('/api/versions/:vid',(req,res)=>{const v=db.prepare('SELECT * FROM versions WHERE id=?').get(req.params.vid) as any;if(!v)return error(res,404,'Version not found.');const pkg=pkgOf(v),items=itemsOf(v);res.json({id:v.id,release_id:v.release_id,version_no:v.version_no,reviewed_by:v.reviewed_by,package:pkg,items,checks:checks(pkg,items),classification:JSON.parse(v.classification)});});
app.post('/api/versions/:vid/generate',async(req,res)=>{const v=db.prepare('SELECT * FROM versions WHERE id=?').get(req.params.vid) as any;if(!v)return error(res,404,'Version not found.');if(v.reviewed_by)return error(res,409,'Human review is already completed for this version.');try{const result=await generate(itemsOf(v),pkgOf(v));db.prepare('DELETE FROM statements WHERE version_id=?').run(v.id);const insert=db.prepare('INSERT INTO statements(version_id,audience,kind,text,status,cites,cite_hashes,scope_hash) VALUES(?,?,?,?,?,?,?,?)');const map=new Map(itemsOf(v).map(i=>[i.id,i.hash]));for(const s of result.statements)insert.run(v.id,s.audience,s.kind,s.text,'pending',JSON.stringify(s.cites),JSON.stringify(Object.fromEntries(s.cites.map(id=>[id,map.get(id)]))),['unsupported_claim','missing_info'].includes(s.kind)?scopeHash(itemsOf(v),s.kind):null);db.prepare('UPDATE versions SET classification=? WHERE id=?').run(JSON.stringify(result.classification),v.id);res.json({...result,statements:statementRows(v.id)});}catch(e){if(e instanceof AIError)return error(res,502,e.message);console.error(JSON.stringify({event:'error',route:'generate',message:String(e)}));return error(res,502,'Draft generation failed. Check AI settings and try again.');}});
app.get('/api/versions/:vid/statements',(req,res)=>{if(!db.prepare('SELECT id FROM versions WHERE id=?').get(req.params.vid))return error(res,404,'Version not found.');res.json(statementRows(Number(req.params.vid)));});
app.patch('/api/statements/:sid',(req,res)=>{const s=db.prepare('SELECT * FROM statements WHERE id=?').get(req.params.sid) as any;if(!s)return error(res,404,'Statement not found.');const v=db.prepare('SELECT * FROM versions WHERE id=?').get(s.version_id) as any;if(v.reviewed_by)return error(res,409,'Review is complete; this statement is locked.');const p=z.object({status:z.enum(['pending','approved','rejected']).optional(),text:z.string().trim().min(1).optional()}).safeParse(req.body);if(!p.success)return error(res,422,'Status or text is invalid; edited text cannot be empty.');if(p.data.text!==undefined&&p.data.text.length>10000)return error(res,422,'Statement text exceeds 10,000 characters.');db.prepare('UPDATE statements SET status=?,edited_text=? WHERE id=?').run(p.data.text!==undefined?'pending':p.data.status??s.status,p.data.text??s.edited_text,s.id);console.log(JSON.stringify({event:'review_action',statement_id:s.id,action:p.data.text!==undefined?'edit':p.data.status}));res.json(statementRows(s.version_id).find(x=>x.id===s.id));});
app.get('/api/compare',(req,res)=>{const a=db.prepare('SELECT * FROM versions WHERE id=?').get(String(req.query.a||'')) as any,b=db.prepare('SELECT * FROM versions WHERE id=?').get(String(req.query.b||'')) as any;if(!a||!b)return error(res,404,'One or both versions were not found.');const older=a.version_no<b.version_no?a:b,newer=older===a?b:a;res.json({diff:diff(itemsOf(older),itemsOf(newer)),stale_statements:statementRows(older.id).filter(s=>s.stale)});});
app.get('/api/versions/:vid/brief',(req,res)=>{const v=db.prepare('SELECT * FROM versions WHERE id=?').get(req.params.vid) as any;if(!v)return error(res,404,'Version not found.');const all=statementRows(v.id),approved=all.filter(s=>s.status==='approved'&&!s.stale),by=(a:string)=>approved.filter(s=>s.audience===a);res.json({status:v.reviewed_by?`human review completed by ${v.reviewed_by}`:'draft - review in progress',reviewed_by:v.reviewed_by,counts:{pending:all.filter(s=>s.status==='pending').length,approved_stale:all.filter(s=>s.status==='approved'&&s.stale).length},checks:checks(pkgOf(v),itemsOf(v)),sections:{technical:by('technical'),stakeholder:by('stakeholder')},risks:approved.filter(s=>['risk','limitation','unsupported_claim'].includes(s.kind)),mode:process.env.AI_API_KEY?'provider':'mock',notice:'Review completion records that a human reviewed the statements. It does not mean the release is approved.'});});
app.post('/api/versions/:vid/complete-review',(req,res)=>{const v=db.prepare('SELECT * FROM versions WHERE id=?').get(req.params.vid) as any;if(!v)return error(res,404,'Version not found.');if(v.reviewed_by)return error(res,409,'Human review is already completed.');const reviewer=typeof req.body?.reviewer==='string'?req.body.reviewer.trim():'';if(!reviewer||reviewer.length>150)return error(res,422,'Enter the reviewer name.');const statements=statementRows(v.id);if(!statements.length)return error(res,409,'Generate statements before completing review.');if(statements.some(s=>s.status==='pending'||s.stale))return error(res,409,'Resolve all pending and stale statements before completing review.');db.prepare('UPDATE versions SET reviewed_by=? WHERE id=?').run(reviewer,v.id);console.log(JSON.stringify({event:'review_completed',version_id:v.id,reviewer}));res.json({status:`human review completed by ${reviewer}`,approved_release:false});});
app.get('/api/health',(_req,res)=>res.json({ok:true}));app.get('*',(req,res,next)=>req.path.startsWith('/api/')?next():res.sendFile(join(process.cwd(),'dist/public/index.html')));app.use((err:any,_req:any,res:any,_next:any)=>{console.error(JSON.stringify({event:'error',message:String(err)}));error(res,422,'Request could not be processed. Check your input.');});
const firstPort=Number(process.env.PORT||3000);if(process.env.NODE_ENV!=='test'){const listen=(port:number)=>{const server=app.listen(port,()=>{console.log(`Release Brief Assistant listening on ${port}`);console.log(`Open: http://localhost:${port}/`);});server.on('error',(err:any)=>{if(err.code==='EADDRINUSE'&&port<firstPort+10){console.warn(`Port ${port} is busy; trying ${port+1}.`);listen(port+1);}else{console.error(`Could not start the server on ports ${firstPort}-${port}: ${err.message}`);process.exitCode=1;}});};listen(firstPort);}export {app};


